version: '3'

services:

  app:
    build: .
    image: daoit/daoit-wifi-station-ap-connect-manual-ssid
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - .:/project
    command: idf.py clean build flash --port /dev/ttyUSB0
  